version: "3.9"

networks:
  backend:
    ipam:
      config:
        - subnet: 172.10.0.0/24

services:
  nginx:
    build: ./appnginx
    container_name: nginxapp
    ports: 
      - 80:80
    networks:
      - backend
    depends_on:
      - app1
      - app2
    volumes: 
      --/data/certs-data/:/data/letsencrypt/
    
  app1:
    build: ./appfastapi
    container_name: app1
    environment:
      - PORT=9000
    ports:
      - 9000:9000
    networks:
      - backend
    hostname: app1
     
  
  app2:
    build: ./appfastapi
    container_name: app2
    environment: 
      - PORT=9001
    ports:
      - 9001:9001
    networks:
      - backend
    hostname: app2